import type { Metadata } from "next";

import localFont from "next/font/local";

import "./globals.css";

const eUkraine = localFont({
  src: [
    {
      path: "../../public/fonts/e-Ukraine-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/e-Ukraine-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/e-Ukraine-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/e-Ukraine-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-eUkraine",
});

export const metadata: Metadata = {
  title: "Vesta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ua">
      <body className={eUkraine.className}>{children}</body>
    </html>
  );
}
